version: '3'
services:
  web:
    build: ./
    depends_on:
    - 'database'
    - 'redis'
    ports:
    - "3004:3004"
    volumes:
    - .:/q-a-service

  database:
    image: mongo

  redis:
    image: redis

  driver:
    build: .
    links:
      - redis